### ISSUE TITLE
no more than 3 songs

### ISSUE THREAD

**Issue by andre409** [Kade-github/BombRushRadio#26]
it won't load the 4th song or I tried to see if it was too big but it worked or I tried taking it off and putting it back on and it didn't work

**Comment by Kade-github** [comment]
I would need to see your file structure. People have loaded way more than 3 songs.

**Comment by andre409** [comment]
in what sense file structure?

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/e4738d7a-f2f2-46fd-8206-e8a04aa8dce2)

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/ab513c41-ce0b-42b1-bdbd-782514a2f9cd)

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/3e5d94a7-7289-4185-92f1-ad53a3ba5e3a)

**Comment by Kade-github** [comment]
do you mind sending me those files? i'd like to test it out myself.

**Comment by andre409** [comment]
ok

**Comment by andre409** [comment]
dll files?

**Comment by andre409** [comment]
[Kade-BombRushRadio-1.4.0.zip](https://github.com/Kade-github/BombRushRadio/files/12704632/Kade-BombRushRadio-1.4.0.zip)

**Comment by andre409** [comment]
update on the situation?

**Comment by Kade-github** [comment]
> [Kade-BombRushRadio-1.4.0.zip](https://github.com/Kade-github/BombRushRadio/files/12704632/Kade-BombRushRadio-1.4.0.zip)

I need the actual song files. Not DLL.

Sorry for not responding.

**Comment by andre409** [comment]
they are in the folder

**Comment by Kade-github** [comment]
alright so like only a couple of these follow the song naming guidelines I set in the readme. 

for future reference:

1. Songs that don't have metadata (aka ripped from youtube or somewhere else) need to be structured in the "SongName-SongArtist.extension" naming convention otherwise it doesn't work.
2. If it does have metadata, and it has a song artist and title, you do not need to name them like this.

Your songs look like this
![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/af02277b-389c-41aa-adb4-62b2c1782f88)


They should look like this

![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/c1c9db4b-0ccc-4e9f-9a9a-2b6b4ec12c55)


As outlined in the readme

![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/8f413c2a-6ac7-4074-88d3-87674ed537fe)

**Comment by andre409** [comment]
I still count 3 songs and I did what you wrote to me
