### ISSUE TITLE
My songs don't appear after the new BRC update

### ISSUE THREAD

**Issue by ChocomintBlight** [Kade-github/BombRushRadio#30]
Since patch 2 added some QoL changes to the music app, i'm wondering if that somehow broke the mod because my songs stopped appearing after the update

**Comment by andre409** [comment]
I don't see any other songs other than the 3 that I posted a long time ago

**Comment by Kade-github** [comment]
> Since patch 2 added some QoL changes to the music app, i'm wondering if that somehow broke the mod because my songs stopped appearing after the update

Hey!

We released a Pre-Release version a day after the public test version came out, which worked just fine.

I had to release a version though that wasn't a pre-release when the update came out, so that's why it broke.

Update is out now, should work fine. Have fun!

![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/fdf62995-ad9f-4ccf-b710-81389b680598)
https://github.com/Kade-github/BombRushRadio/releases/tag/1.6
